import React from "react";
import "./ComplianceModal.css";

const ComplianceModal = ({ onAcknowledge }) => {
  return (
    <div className="compliance-overlay">
      <div className="compliance-box">
        <h3>🔒 Data Protection Notice</h3>

        <p>
          Sky UK Limited is offering this trial to help you self-assess your capability against the Sky Skill areas. 
          We’ll also use the data generated by it to carry out analysis to identify learning opportunities for particular 
          demographics within Sky and work towards our goal of making the company a more inclusive place to work.  
        </p>

        <p>
          The analysis doesn’t focus on individual answers. Instead, we will combine the result we receive together 
          to look at them in groups to finds trends and patterns. We’ll also combine this data with the information you’ve
          provided previously to Sky on Workday about your race/ethnicity, religion, sexual orientation, gender identity,
          disability and social mobility, as well as other information we hold on you (such as your salary band,
          what part of Sky you work in, your nationality and your marital status) to identify trends and patterns 
          to ensure Sky is creating an inclusive workplace with equal opportunities for all.  
        </p>

        <p>Participation is voluntary and we will take steps to ensure your answers are kept confidential.</p>

        <p>
          The information will be accessible by the D&I Team, the Learning & Development team and People Analytics. 
          We will keep the results and the analysis we carry out for one year, unless we need to keep it longer 
          to fulfil the purpose set out above. The data will not be transferred outside the UK and the EU. 
        </p>

        <p>
          We will use your data for this where we have a valid legitimate interest in ensuring equality of opportunity and treatment 
          within Sky and make the company a more inclusive place to work. We only use the information you’ve provided about yourself 
          via Workday when you have consented to sharing it with us. You can alter the details provided on Workday{" "}
          <a href="https://wd3.myworkday.com/sky/d/task/2997$4586.htmld" target="_blank" rel="noopener noreferrer">
            here
          </a>{" "}
          or contact us at <a href="mailto:inclusion@sky.uk">inclusion@sky.uk</a> to object to us using your data in this way.
        </p>

        <p>
          If you are in the UK or Ireland, please see our employee privacy notice for more information of how Sky uses your personal data and your rights, 
          which you can find{" "}
          <a href="https://people.at.sky/skylife?id=kb_article_view&sys_kb_id=8fb8c9cf830b521010017cf16daad33a" target="_blank" rel="noopener noreferrer">
            here
          </a>.
        </p>

        <button className="compliance-btn" onClick={onAcknowledge}>
          I Acknowledge
        </button>
      </div>
    </div>
  );
};

export default ComplianceModal;
